'use strict';
const menu=document.querySelector('.menu'),nav=document.querySelector('#navigation');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}));
document.querySelectorAll('[data-answer]').forEach(button=>button.addEventListener('click',()=>{const after=button.dataset.answer==='after';document.querySelectorAll('[data-answer]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});const detail=document.querySelector('#answer-detail');detail.textContent=after?'Its approved company facts specify weekday support hours and the Denver metro service area.':'Its support hours and service coverage aren’t clear from the available information.';detail.classList.toggle('reviewed',after);const status=document.querySelector('#answer-status');status.textContent=after?'2 facts clarified in this example':'2 facts need attention';status.className='status '+(after?'green':'orange');document.querySelector('#fact-title').textContent=after?'Reviewed facts. Ready for the next step.':'Your facts. One reliable source.';document.querySelector('#fact-description').textContent=after?'Illustration only. Actual AI answers may differ.':'Review support hours and service coverage.'}));
const workflow={observe:{label:'ANSWER EVIDENCE',title:'A mention is only the beginning.',text:'Look at what buyers actually hear about your business. Review the supporting sources and pinpoint incomplete or inaccurate facts.',rows:[['Sample answer accuracy','31 of 40 claims'],['Missing detail','Support coverage'],['Next step','Review the evidence']],link:'answers',cta:'Explore sample answers'},correct:{label:'COMPANY FACTS',title:'Make the source of truth explicit.',text:'Keep approved services, locations and policies together. Trace each fact to its source and see which pages depend on it.',rows:[['Fact','Support hours'],['Review state','Owner approval required'],['Dependency','Service information page']],link:'facts',cta:'Review the sample fact base'},publish:{label:'APPROVED IMPROVEMENTS',title:'Every change has a reason.',text:'Review a draft, check its approved facts and resolve access issues before a simulated publish. Keep the owner in control.',rows:[['Proposed change','Clarify service coverage'],['Approval','Required before publishing'],['This preview','No external changes']],link:'plan',cta:'Explore the work plan'},measure:{label:'ENQUIRY EVIDENCE',title:'Know what the data can tell you.',text:'See activity and outcomes side by side. Distinguish an AI referral, a buyer’s own report and an unknown source without overstating attribution.',rows:[['Sample qualified enquiries','11'],['Source evidence','Reported / referred / unknown'],['Causal impact','Not established']],link:'enquiries',cta:'Explore enquiry evidence'}};
const tabs=[...document.querySelectorAll('[data-step]')];
function selectStep(tab){tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1});const d=workflow[tab.dataset.step],panel=document.querySelector('#workflow-panel');panel.setAttribute('aria-labelledby',tab.id);panel.innerHTML=`<div class="panel-top"><span>${d.label}</span><span>FICTIONAL WORKSPACE</span></div><h3>${d.title}</h3><p>${d.text}</p>${d.rows.map(([a,b])=>`<div class="evidence-row"><span>${a}</span><strong>${b}</strong></div>`).join('')}<a href="dashboard/index.html#${d.link}">${d.cta} ↗</a>`}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectStep(tab));tab.addEventListener('keydown',e=>{let n;if(e.key==='ArrowDown')n=(i+1)%tabs.length;if(e.key==='ArrowUp')n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();selectStep(tabs[n]);tabs[n].focus()}})});selectStep(tabs[0]);
const dialog=document.querySelector('#preview-dialog'),content=document.querySelector('#dialog-content');
document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.querySelectorAll('[data-audit]').forEach(b=>b.addEventListener('click',()=>{content.innerHTML='<h2 id="dialog-title">What an answer audit can reveal.</h2><p>Example audit · Northstar IT, a fictional managed IT business. These are sample findings, not a live scan.</p><div class="audit-row"><span>Answer accuracy</span><strong>31 / 40 claims correct</strong></div><div class="audit-row"><span>Fact to clarify</span><strong>Support coverage</strong></div><div class="audit-row"><span>Access review</span><strong>Check engine access</strong></div><div class="audit-row"><span>Recommended first step</span><strong>Review approved facts</strong></div><p>Explore the diagnosis, compare the supporting evidence and try the approval workflow. No website connection or contact details needed.</p><a class="button purple" href="dashboard/index.html#diagnosis">Open the sample diagnosis ↗</a>';dialog.showModal()}));
document.querySelector('[data-privacy]').addEventListener('click',()=>{content.innerHTML='<h2 id="dialog-title">Privacy in this preview.</h2><p>This marketing page does not collect contact details, submit forms or run analytics. The dashboard saves demo changes in local storage in your browser; its Reset control clears that demo state.</p><p>Typography is loaded from Google Fonts, which receives ordinary connection information such as your IP address. The hosting provider may also record standard web request information. There are no live AI, CRM or website integrations.</p><p>This explains the current preview only. A production privacy policy will be needed before launching accounts or collecting customer data.</p>';dialog.showModal()});
